/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmSplash.java
 *
 * Created on Apr 8, 2010, 1:53:56 PM
 */

package Formularios;

/**
 *
 * @author indigovox
 */
public class FrmSplash extends javax.swing.JFrame {

    /** Creates new form FrmSplash */
    public FrmSplash() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel2 = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      BtnSplashOk = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Informações sobre o TMW-Maker");
      setName("FrmSplash"); // NOI18N
      setResizable(false);
      setUndecorated(true);

      jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 36));
      jLabel2.setForeground(javax.swing.UIManager.getDefaults().getColor("Label.foreground"));
      jLabel2.setText("TMW MAKER");
      jLabel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
      jLabel2.setFocusable(false);
      jLabel2.setInheritsPopupMenu(false);
      jLabel2.setRequestFocusEnabled(false);
      jLabel2.setVerifyInputWhenFocusTarget(false);

      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fundos/splash.png"))); // NOI18N

      jLabel3.setText("VERSÃO: 0.2");

      jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
      jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel4.setText("DESENVOLVEDORA:");

      jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
      jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel5.setText("LICENÇA:");

      jLabel6.setText("www.themanaworld.com.br");

      jLabel7.setText("GPL OpenSource");

      jLabel8.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
      jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel8.setText("LANÇAMENTO:");

      jLabel9.setText("2010-04-08");

      BtnSplashOk.setMnemonic('O');
      BtnSplashOk.setText("Ok");
      BtnSplashOk.setName("BtnSplashOk"); // NOI18N
      BtnSplashOk.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnSplashOkActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel2)
                     .addComponent(jLabel3)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addComponent(jLabel8)
                           .addComponent(jLabel5)
                           .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel9)
                           .addComponent(jLabel6)
                           .addComponent(jLabel7)))))
               .addGroup(layout.createSequentialGroup()
                  .addGap(91, 91, 91)
                  .addComponent(BtnSplashOk, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel1)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addGap(40, 40, 40)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(jLabel6))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel9)
               .addComponent(jLabel8))
            .addGap(190, 190, 190)
            .addComponent(BtnSplashOk))
      );

      getAccessibleContext().setAccessibleParent(this);

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void BtnSplashOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSplashOkActionPerformed
       // TODO add your handling code here:
       //javax.swing.JFrame FrmPrincipal = new Principal();
       //FrmPrincipal.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BtnSplashOkActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSplash().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnSplashOk;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   // End of variables declaration//GEN-END:variables

}
