/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPrincipal.java
 *
 * Created on Apr 8, 2010, 2:20:48 PM
 */
package Formularios;

import java.awt.Dialog.ModalExclusionType;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author indigovox
 */
public class FrmPrincipal extends javax.swing.JFrame {

   static String ComponenteSelecionado = "";

   /*public void setFocoEmComponente(String NomeDoComponente) {
      ComponenteSelecionado = NomeDoComponente.toString();
   }/**/

   /** Creates new form FrmPrincipal */
   public FrmPrincipal() {
      initComponents();
   }

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      MnuSistema = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      jMenuItem2 = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JSeparator();
      jMenuItem3 = new javax.swing.JMenuItem();
      MnuSistemaAlteracoes = new javax.swing.JMenuItem();
      jSeparator2 = new javax.swing.JSeparator();
      MnuSistemaFechar = new javax.swing.JMenuItem();
      MnuEditar = new javax.swing.JMenu();
      MnuEditarItens = new javax.swing.JMenu();
      MnuEditarItensSprites = new javax.swing.JMenuItem();
      MnuEditarItensDados = new javax.swing.JMenuItem();
      MnuEditarCampos = new javax.swing.JMenu();
      MnuEditarCamposTilesets = new javax.swing.JMenuItem();
      MnuEditarCamposPortais = new javax.swing.JMenuItem();
      MnuEditarCamposMapas = new javax.swing.JMenuItem();
      MnuEditarPersonagem = new javax.swing.JMenu();
      MnuEditarPersonagemAparencia = new javax.swing.JMenuItem();
      MnuEditarPersonagemLoja = new javax.swing.JMenuItem();
      MnuEditarPersonagemScript = new javax.swing.JMenuItem();
      MnuEditarInimigos = new javax.swing.JMenu();
      MnuEditarInimigosAnimacao = new javax.swing.JMenuItem();
      MnuEditarInimigosDados = new javax.swing.JMenuItem();
      MnuEditarInimigosArenas = new javax.swing.JMenuItem();
      MnuEditarMagias = new javax.swing.JMenu();
      MnuEditarMagiasCompetencias = new javax.swing.JMenuItem();
      MnuEditarMagiasConjurações = new javax.swing.JMenuItem();
      jSeparator3 = new javax.swing.JSeparator();
      MnuEditarPoderGM = new javax.swing.JMenuItem();
      jMenuItem6 = new javax.swing.JMenuItem();
      jMenu4 = new javax.swing.JMenu();
      jMenuItem7 = new javax.swing.JMenuItem();
      jMenuItem8 = new javax.swing.JMenuItem();
      jMenu5 = new javax.swing.JMenu();
      jMenuItem9 = new javax.swing.JMenuItem();
      MnuAjudaComentarios = new javax.swing.JMenuItem();
      jMenuItem11 = new javax.swing.JMenuItem();
      jSeparator4 = new javax.swing.JSeparator();
      MnuAjudaSobre = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("TMW-MAKER 0.2");
      setForeground(java.awt.Color.white);
      addComponentListener(new java.awt.event.ComponentAdapter() {
         public void componentShown(java.awt.event.ComponentEvent evt) {
            formComponentShown(evt);
         }
      });

      jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fundos/floresta_1024x768.png"))); // NOI18N
      jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

      MnuSistema.setMnemonic('S');
      MnuSistema.setText("Sistema");

      jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_UP, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem1.setMnemonic('E');
      jMenuItem1.setText("Enviar");
      jMenuItem1.setEnabled(false);
      MnuSistema.add(jMenuItem1);

      jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_DOWN, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem2.setMnemonic('R');
      jMenuItem2.setText("Receber");
      jMenuItem2.setEnabled(false);
      MnuSistema.add(jMenuItem2);
      MnuSistema.add(jSeparator1);

      jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem3.setMnemonic('G');
      jMenuItem3.setText("Configurações");
      jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
         }
      });
      MnuSistema.add(jMenuItem3);

      MnuSistemaAlteracoes.setText("Alterações");
      MnuSistemaAlteracoes.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            MnuSistemaAlteracoesActionPerformed(evt);
         }
      });
      MnuSistema.add(MnuSistemaAlteracoes);
      MnuSistema.add(jSeparator2);

      MnuSistemaFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
      MnuSistemaFechar.setMnemonic('F');
      MnuSistemaFechar.setText("Fechar");
      MnuSistemaFechar.setName("BtnPrincipalFechar"); // NOI18N
      MnuSistemaFechar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            MnuSistemaFecharActionPerformed(evt);
         }
      });
      MnuSistema.add(MnuSistemaFechar);
      MnuSistemaFechar.getAccessibleContext().setAccessibleName("BtnPrincipalFechar");

      jMenuBar1.add(MnuSistema);

      MnuEditar.setMnemonic('E');
      MnuEditar.setText("Editar");

      MnuEditarItens.setMnemonic('I');
      MnuEditarItens.setText("Itens");

      MnuEditarItensSprites.setMnemonic('S');
      MnuEditarItensSprites.setText("Sprites");
      MnuEditarItensSprites.setEnabled(false);
      MnuEditarItens.add(MnuEditarItensSprites);

      MnuEditarItensDados.setMnemonic('D');
      MnuEditarItensDados.setText("Dados");
      MnuEditarItensDados.setEnabled(false);
      MnuEditarItens.add(MnuEditarItensDados);

      MnuEditar.add(MnuEditarItens);

      MnuEditarCampos.setMnemonic('C');
      MnuEditarCampos.setText("Campos");

      MnuEditarCamposTilesets.setMnemonic('T');
      MnuEditarCamposTilesets.setText("Tilesets");
      MnuEditarCamposTilesets.setEnabled(false);
      MnuEditarCampos.add(MnuEditarCamposTilesets);

      MnuEditarCamposPortais.setMnemonic('P');
      MnuEditarCamposPortais.setText("Portais");
      MnuEditarCamposPortais.setEnabled(false);
      MnuEditarCampos.add(MnuEditarCamposPortais);

      MnuEditarCamposMapas.setMnemonic('M');
      MnuEditarCamposMapas.setText("Mini-mapas");
      MnuEditarCamposMapas.setEnabled(false);
      MnuEditarCampos.add(MnuEditarCamposMapas);

      MnuEditar.add(MnuEditarCampos);

      MnuEditarPersonagem.setMnemonic('P');
      MnuEditarPersonagem.setText("Personagem");

      MnuEditarPersonagemAparencia.setMnemonic('A');
      MnuEditarPersonagemAparencia.setText("Aparencia");
      MnuEditarPersonagemAparencia.setEnabled(false);
      MnuEditarPersonagem.add(MnuEditarPersonagemAparencia);

      MnuEditarPersonagemLoja.setMnemonic('L');
      MnuEditarPersonagemLoja.setText("Loja");
      MnuEditarPersonagemLoja.setEnabled(false);
      MnuEditarPersonagem.add(MnuEditarPersonagemLoja);

      MnuEditarPersonagemScript.setMnemonic('S');
      MnuEditarPersonagemScript.setText("Script");
      MnuEditarPersonagemScript.setEnabled(false);
      MnuEditarPersonagem.add(MnuEditarPersonagemScript);

      MnuEditar.add(MnuEditarPersonagem);

      MnuEditarInimigos.setMnemonic('N');
      MnuEditarInimigos.setText("Inimigos");

      MnuEditarInimigosAnimacao.setMnemonic('A');
      MnuEditarInimigosAnimacao.setText("Animação");
      MnuEditarInimigosAnimacao.setEnabled(false);
      MnuEditarInimigos.add(MnuEditarInimigosAnimacao);

      MnuEditarInimigosDados.setMnemonic('D');
      MnuEditarInimigosDados.setText("Dados");
      MnuEditarInimigosDados.setEnabled(false);
      MnuEditarInimigos.add(MnuEditarInimigosDados);

      MnuEditarInimigosArenas.setMnemonic('R');
      MnuEditarInimigosArenas.setText("Arenas");
      MnuEditarInimigosArenas.setEnabled(false);
      MnuEditarInimigos.add(MnuEditarInimigosArenas);

      MnuEditar.add(MnuEditarInimigos);

      MnuEditarMagias.setMnemonic('M');
      MnuEditarMagias.setText("Magias");

      MnuEditarMagiasCompetencias.setMnemonic('M');
      MnuEditarMagiasCompetencias.setText("Competencias");
      MnuEditarMagiasCompetencias.setEnabled(false);
      MnuEditarMagias.add(MnuEditarMagiasCompetencias);

      MnuEditarMagiasConjurações.setMnemonic('C');
      MnuEditarMagiasConjurações.setText("Conjurações");
      MnuEditarMagiasConjurações.setEnabled(false);
      MnuEditarMagias.add(MnuEditarMagiasConjurações);

      MnuEditar.add(MnuEditarMagias);
      MnuEditar.add(jSeparator3);

      MnuEditarPoderGM.setText("Poder GM");
      MnuEditarPoderGM.setEnabled(false);
      MnuEditar.add(MnuEditarPoderGM);

      jMenuItem6.setMnemonic('A');
      jMenuItem6.setText("Partículas");
      jMenuItem6.setEnabled(false);
      MnuEditar.add(jMenuItem6);

      jMenuBar1.add(MnuEditar);

      jMenu4.setMnemonic('J');
      jMenu4.setText("Jogo");

      jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
      jMenuItem7.setMnemonic('E');
      jMenuItem7.setText("Executar");
      jMenuItem7.setEnabled(false);
      jMenu4.add(jMenuItem7);

      jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem8.setMnemonic('S');
      jMenuItem8.setText("Estruturar");
      jMenuItem8.setEnabled(false);
      jMenu4.add(jMenuItem8);

      jMenuBar1.add(jMenu4);

      jMenu5.setMnemonic('A');
      jMenu5.setText("Ajuda");

      jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
      jMenuItem9.setMnemonic('P');
      jMenuItem9.setText("Componentes");
      jMenuItem9.setEnabled(false);
      jMenu5.add(jMenuItem9);

      MnuAjudaComentarios.setMnemonic('C');
      MnuAjudaComentarios.setText("Comentários");
      MnuAjudaComentarios.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            MnuAjudaComentariosActionPerformed(evt);
         }
      });
      jMenu5.add(MnuAjudaComentarios);

      jMenuItem11.setText("Traduções");
      jMenuItem11.setEnabled(false);
      jMenu5.add(jMenuItem11);
      jMenu5.add(jSeparator4);

      MnuAjudaSobre.setText("Sobre...");
      MnuAjudaSobre.setName("MnuPrincipalSobre"); // NOI18N
      MnuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            MnuAjudaSobreActionPerformed(evt);
         }
      });
      jMenu5.add(MnuAjudaSobre);
      MnuAjudaSobre.getAccessibleContext().setAccessibleName("MnuPrincipalSobre");

      jMenuBar1.add(jMenu5);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 725, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void MnuSistemaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSistemaFecharActionPerformed
       // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_MnuSistemaFecharActionPerformed

    private void MnuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAjudaSobreActionPerformed
       // TODO add your handling code here:
       javax.swing.JDialog FrmSplash = new FrmSplash(this, rootPaneCheckingEnabled);
       FrmSplash.setLocation(
               ((this.getWidth() - FrmSplash.getWidth()) / 2) + this.getX(),
               ((this.getHeight() - FrmSplash.getHeight()) / 2) + this.getY());
       FrmSplash.pack();
       FrmSplash.setModal(true);
       FrmSplash.setVisible(true);/**/
    }//GEN-LAST:event_MnuAjudaSobreActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       // TODO add your handling code here:
       Dimension Tela = Toolkit.getDefaultToolkit().getScreenSize();
       this.setBounds(
               (Tela.width - this.getWidth()) / 2,
               (Tela.height - this.getHeight()) / 2,
               this.getWidth(),
               this.getHeight());
       //this.setExtendedState(MAXIMIZED_BOTH); //Maximiza a tela

    }//GEN-LAST:event_formComponentShown

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       // TODO add your handling code here:
       javax.swing.JDialog FrmConfiguracao = new FrmConfiguracao(this, rootPaneCheckingEnabled);
       FrmConfiguracao.setLocation(
               ((this.getWidth() - FrmConfiguracao.getWidth()) / 2) + this.getX(),
               ((this.getHeight() - FrmConfiguracao.getHeight()) / 2) + this.getY());
       FrmConfiguracao.pack();
       FrmConfiguracao.setModal(true);
       FrmConfiguracao.setVisible(true);/**/
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public static boolean AbrirNavegador(String URL) {
      //minimizes the app

      String SistemaOperacional = System.getProperty("os.name").toLowerCase();
      Runtime rt = Runtime.getRuntime();
      try {
         if (SistemaOperacional.indexOf("win") >= 0) {
            String[] cmd = new String[4];
            cmd[0] = "cmd.exe";
            cmd[1] = "/C";
            cmd[2] = "start";
            cmd[3] = URL;
            rt.exec(cmd);
         } else if (SistemaOperacional.indexOf("mac") >= 0) {
            rt.exec("open " + URL);
         } else {
            //prioritized 'guess' of users' preference
            String[] browsers = {"epiphany", "firefox", "mozilla", "konqueror", "netscape", "opera", "links", "lynx"};

            StringBuffer cmd = new StringBuffer();
            for (int i = 0; i < browsers.length; i++) {
               cmd.append((i == 0 ? "" : " || ") + browsers[i] + " \"" +
                       URL + "\" ");
            }

            rt.exec(new String[]{"sh", "-c", cmd.toString()});
            //rt.exec("firefox http://www.google.com");
            //System.out.println(cmd.toString());

         }
      } catch (IOException e) {
         e.printStackTrace();
         JOptionPane.showMessageDialog(
            null,
            "\n\n The system failed to invoke your default web browser while attempting to access: \n\n " + URL + "\n\n",
            "Browser Error",
            JOptionPane.WARNING_MESSAGE
         );

        return false;
    }
    return true;
   }

    private void MnuSistemaAlteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSistemaAlteracoesActionPerformed
       // TODO add your handling code here:
       AbrirNavegador("http://code.google.com/p/tmw-maker/source/list");
    }//GEN-LAST:event_MnuSistemaAlteracoesActionPerformed

    private void MnuAjudaComentariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAjudaComentariosActionPerformed
       // TODO add your handling code here:
       AbrirNavegador("http://code.google.com/p/tmw-maker/issues/entry");
    }//GEN-LAST:event_MnuAjudaComentariosActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new FrmPrincipal().setVisible(true);
         }
      });
   }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem MnuAjudaComentarios;
   private javax.swing.JMenuItem MnuAjudaSobre;
   private javax.swing.JMenu MnuEditar;
   private javax.swing.JMenu MnuEditarCampos;
   private javax.swing.JMenuItem MnuEditarCamposMapas;
   private javax.swing.JMenuItem MnuEditarCamposPortais;
   private javax.swing.JMenuItem MnuEditarCamposTilesets;
   private javax.swing.JMenu MnuEditarInimigos;
   private javax.swing.JMenuItem MnuEditarInimigosAnimacao;
   private javax.swing.JMenuItem MnuEditarInimigosArenas;
   private javax.swing.JMenuItem MnuEditarInimigosDados;
   private javax.swing.JMenu MnuEditarItens;
   private javax.swing.JMenuItem MnuEditarItensDados;
   private javax.swing.JMenuItem MnuEditarItensSprites;
   private javax.swing.JMenu MnuEditarMagias;
   private javax.swing.JMenuItem MnuEditarMagiasCompetencias;
   private javax.swing.JMenuItem MnuEditarMagiasConjurações;
   private javax.swing.JMenu MnuEditarPersonagem;
   private javax.swing.JMenuItem MnuEditarPersonagemAparencia;
   private javax.swing.JMenuItem MnuEditarPersonagemLoja;
   private javax.swing.JMenuItem MnuEditarPersonagemScript;
   private javax.swing.JMenuItem MnuEditarPoderGM;
   private javax.swing.JMenu MnuSistema;
   private javax.swing.JMenuItem MnuSistemaAlteracoes;
   private javax.swing.JMenuItem MnuSistemaFechar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JMenu jMenu4;
   private javax.swing.JMenu jMenu5;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem11;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JMenuItem jMenuItem6;
   private javax.swing.JMenuItem jMenuItem7;
   private javax.swing.JMenuItem jMenuItem8;
   private javax.swing.JMenuItem jMenuItem9;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   // End of variables declaration//GEN-END:variables
}
