/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmSplash.java
 *
 * Created on Apr 9, 2010, 1:19:42 PM
 */

package Formularios;

/**
 *
 * @author indigovox
 */
public class FrmSplash extends javax.swing.JDialog {

    /** Creates new form FrmSplash */
    public FrmSplash(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

      /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      BtnSplashOk = new javax.swing.JButton();
      LblDesenvolvedora = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setModal(true);
      setResizable(false);
      setUndecorated(true);

      jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Fundos/splash.png"))); // NOI18N

      jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 36));
      jLabel2.setText("TMW MAKER");

      jLabel3.setText("<html><b>VERSÃO 0.2</b> (GLP Open Source)");

      BtnSplashOk.setText("OK");
      BtnSplashOk.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            BtnSplashOkActionPerformed(evt);
         }
      });

      LblDesenvolvedora.setText("<html><a href=\"http://code.google.com/p/tmw-maker\">http://code.google.com/p/tmw-maker</a></html>");
      LblDesenvolvedora.setInheritsPopupMenu(false);
      LblDesenvolvedora.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            LblDesenvolvedoraMouseClicked(evt);
         }
      });

      jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
      jLabel5.setText("DESENVOLVEDORA:");

      jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 13));
      jLabel6.setText("CONTATO:");

      jLabel7.setText("<html><a href=\"mailto:rui.gravata@hotmail.com\">rui.gravata@hotmail.com</a></html>");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel2)
                     .addComponent(jLabel3)
                     .addComponent(jLabel5)
                     .addComponent(LblDesenvolvedora)
                     .addComponent(jLabel7)
                     .addComponent(jLabel6)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(90, 90, 90)
                  .addComponent(BtnSplashOk, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(16, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jLabel1)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(LblDesenvolvedora)
            .addGap(18, 18, 18)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
            .addComponent(BtnSplashOk)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void BtnSplashOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSplashOkActionPerformed
       // TODO add your handling code here:
       this.dispose();
    }//GEN-LAST:event_BtnSplashOkActionPerformed

    private void LblDesenvolvedoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblDesenvolvedoraMouseClicked
       // TODO add your handling code here:
       FrmPrincipal.AbrirNavegador("http://code.google.com/p/tmw-maker");
    }//GEN-LAST:event_LblDesenvolvedoraMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSplash dialog = new FrmSplash(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton BtnSplashOk;
   private javax.swing.JLabel LblDesenvolvedora;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   // End of variables declaration//GEN-END:variables

}
