/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on Apr 8, 2010, 2:20:48 PM
 */

package Formularios;

/**
 *
 * @author indigovox
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      jMenuItem1 = new javax.swing.JMenuItem();
      jMenuItem2 = new javax.swing.JMenuItem();
      jSeparator1 = new javax.swing.JSeparator();
      jMenuItem3 = new javax.swing.JMenuItem();
      jMenuItem4 = new javax.swing.JMenuItem();
      jSeparator2 = new javax.swing.JSeparator();
      MnuSistemaFechar = new javax.swing.JMenuItem();
      jMenu2 = new javax.swing.JMenu();
      jMenu3 = new javax.swing.JMenu();
      MnuEditarItensImagem = new javax.swing.JMenuItem();
      MnuEditarItensDados = new javax.swing.JMenuItem();
      jMenu6 = new javax.swing.JMenu();
      jMenu7 = new javax.swing.JMenu();
      jMenu8 = new javax.swing.JMenu();
      jMenu9 = new javax.swing.JMenu();
      jSeparator3 = new javax.swing.JSeparator();
      MnuEditarPoderGM = new javax.swing.JMenuItem();
      jMenu4 = new javax.swing.JMenu();
      jMenuItem7 = new javax.swing.JMenuItem();
      jMenuItem8 = new javax.swing.JMenuItem();
      jMenu5 = new javax.swing.JMenu();
      jMenuItem9 = new javax.swing.JMenuItem();
      jMenuItem10 = new javax.swing.JMenuItem();
      jMenuItem11 = new javax.swing.JMenuItem();
      jSeparator4 = new javax.swing.JSeparator();
      MnuAjudaSobre = new javax.swing.JMenuItem();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("TMW-MAKER 0.2");

      jMenu1.setMnemonic('S');
      jMenu1.setText("Sistema");

      jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_UP, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem1.setMnemonic('E');
      jMenuItem1.setText("Enviar");
      jMenuItem1.setEnabled(false);
      jMenu1.add(jMenuItem1);

      jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PAGE_DOWN, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem2.setMnemonic('R');
      jMenuItem2.setText("Receber");
      jMenuItem2.setEnabled(false);
      jMenu1.add(jMenuItem2);
      jMenu1.add(jSeparator1);

      jMenuItem3.setMnemonic('G');
      jMenuItem3.setText("Configurações");
      jMenuItem3.setEnabled(false);
      jMenu1.add(jMenuItem3);

      jMenuItem4.setText("Alterações");
      jMenuItem4.setEnabled(false);
      jMenu1.add(jMenuItem4);
      jMenu1.add(jSeparator2);

      MnuSistemaFechar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
      MnuSistemaFechar.setMnemonic('F');
      MnuSistemaFechar.setText("Fechar");
      MnuSistemaFechar.setName("BtnPrincipalFechar"); // NOI18N
      MnuSistemaFechar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            MnuSistemaFecharActionPerformed(evt);
         }
      });
      jMenu1.add(MnuSistemaFechar);
      MnuSistemaFechar.getAccessibleContext().setAccessibleName("BtnPrincipalFechar");

      jMenuBar1.add(jMenu1);

      jMenu2.setMnemonic('E');
      jMenu2.setText("Editar");

      jMenu3.setMnemonic('I');
      jMenu3.setText("Itens");

      MnuEditarItensImagem.setMnemonic('I');
      MnuEditarItensImagem.setText("Imagens");
      MnuEditarItensImagem.setEnabled(false);
      jMenu3.add(MnuEditarItensImagem);

      MnuEditarItensDados.setMnemonic('D');
      MnuEditarItensDados.setText("Dados");
      MnuEditarItensDados.setEnabled(false);
      jMenu3.add(MnuEditarItensDados);

      jMenu2.add(jMenu3);

      jMenu6.setMnemonic('C');
      jMenu6.setText("Campos");
      jMenu2.add(jMenu6);

      jMenu7.setMnemonic('P');
      jMenu7.setText("Personagens");
      jMenu2.add(jMenu7);

      jMenu8.setMnemonic('M');
      jMenu8.setText("Monstros");
      jMenu2.add(jMenu8);

      jMenu9.setMnemonic('C');
      jMenu9.setText("Conjurações");
      jMenu2.add(jMenu9);
      jMenu2.add(jSeparator3);

      MnuEditarPoderGM.setText("Poder GM");
      MnuEditarPoderGM.setEnabled(false);
      jMenu2.add(MnuEditarPoderGM);

      jMenuBar1.add(jMenu2);

      jMenu4.setMnemonic('J');
      jMenu4.setText("Jogo");

      jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
      jMenuItem7.setMnemonic('E');
      jMenuItem7.setText("Executar");
      jMenuItem7.setEnabled(false);
      jMenu4.add(jMenuItem7);

      jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, java.awt.event.InputEvent.CTRL_MASK));
      jMenuItem8.setMnemonic('E');
      jMenuItem8.setText("Estruturar");
      jMenuItem8.setEnabled(false);
      jMenu4.add(jMenuItem8);

      jMenuBar1.add(jMenu4);

      jMenu5.setMnemonic('A');
      jMenu5.setText("Ajuda");

      jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
      jMenuItem9.setMnemonic('P');
      jMenuItem9.setText("Componentes");
      jMenuItem9.setEnabled(false);
      jMenu5.add(jMenuItem9);

      jMenuItem10.setText("Comentários");
      jMenuItem10.setEnabled(false);
      jMenu5.add(jMenuItem10);

      jMenuItem11.setText("Traduções");
      jMenuItem11.setEnabled(false);
      jMenu5.add(jMenuItem11);
      jMenu5.add(jSeparator4);

      MnuAjudaSobre.setText("Sobre...");
      MnuAjudaSobre.setName("MnuPrincipalSobre"); // NOI18N
      MnuAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            MnuAjudaSobreActionPerformed(evt);
         }
      });
      jMenu5.add(MnuAjudaSobre);
      MnuAjudaSobre.getAccessibleContext().setAccessibleName("MnuPrincipalSobre");

      jMenuBar1.add(jMenu5);

      setJMenuBar(jMenuBar1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 400, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 277, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void MnuSistemaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuSistemaFecharActionPerformed
       // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_MnuSistemaFecharActionPerformed

    private void MnuAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnuAjudaSobreActionPerformed
       // TODO add your handling code here:
       javax.swing.JFrame FrmSplash = new FrmSplash();
       FrmSplash.setVisible(true);
    }//GEN-LAST:event_MnuAjudaSobreActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JMenuItem MnuAjudaSobre;
   private javax.swing.JMenuItem MnuEditarItensDados;
   private javax.swing.JMenuItem MnuEditarItensImagem;
   private javax.swing.JMenuItem MnuEditarPoderGM;
   private javax.swing.JMenuItem MnuSistemaFechar;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenu jMenu2;
   private javax.swing.JMenu jMenu3;
   private javax.swing.JMenu jMenu4;
   private javax.swing.JMenu jMenu5;
   private javax.swing.JMenu jMenu6;
   private javax.swing.JMenu jMenu7;
   private javax.swing.JMenu jMenu8;
   private javax.swing.JMenu jMenu9;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JMenuItem jMenuItem10;
   private javax.swing.JMenuItem jMenuItem11;
   private javax.swing.JMenuItem jMenuItem2;
   private javax.swing.JMenuItem jMenuItem3;
   private javax.swing.JMenuItem jMenuItem4;
   private javax.swing.JMenuItem jMenuItem7;
   private javax.swing.JMenuItem jMenuItem8;
   private javax.swing.JMenuItem jMenuItem9;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JSeparator jSeparator2;
   private javax.swing.JSeparator jSeparator3;
   private javax.swing.JSeparator jSeparator4;
   // End of variables declaration//GEN-END:variables

}
