/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmPrincipal.java
 *
 * Created on 01/06/2012, 09:19:46
 */
package formularios;

import classes.FileClass;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author lunovox
 */
public class FrmPrincipal extends javax.swing.JFrame {

	/** Creates new form FrmPrincipal */
	public FrmPrincipal() {
		super.setIconImage((new ImageIcon(getClass().getResource("/imagens/keys_small.gif"))).getImage());
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btnSelecionar = new javax.swing.JButton();
      lblArquivo1 = new javax.swing.JLabel();
      txtCheckSum = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Grafic Adler32");
      setResizable(false);
      addWindowListener(new java.awt.event.WindowAdapter() {
         public void windowOpened(java.awt.event.WindowEvent evt) {
            formWindowOpened(evt);
         }
      });

      btnSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/open16.png"))); // NOI18N
      btnSelecionar.setText("Selecionar");
      btnSelecionar.setToolTipText("Selecione um arquivo para gerar o numero Checksum Adler32");
      btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSelecionarActionPerformed(evt);
         }
      });

      lblArquivo1.setText("CheckSum:");

      txtCheckSum.setBackground(java.awt.SystemColor.controlHighlight);
      txtCheckSum.setEditable(false);
      txtCheckSum.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
      txtCheckSum.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      txtCheckSum.setText("-----------");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblArquivo1)
            .addGap(6, 6, 6)
            .addComponent(txtCheckSum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSelecionar)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(txtCheckSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(lblArquivo1)
               .addComponent(btnSelecionar))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSelecionar, lblArquivo1, txtCheckSum});

      pack();
   }// </editor-fold>//GEN-END:initComponents

	 private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
		 // TODO add your handling code here:
		 /**
		  * Material Pesquisado em:
		  * http://java.sun.com/docs/books/tutorial/uiswing/components/filechooser.html
		  * http://www.koders.com/java/fid3C76E6EFEBC0827517FB14397E0D8E9E5126DD92.aspx
		  */
		 //Handle open button action.
		 //evt.getSource() == openButton
		 //Create a file chooser
		 final JFileChooser Dialogo = new JFileChooser();
		 //Dialogo.setFileFilter(new FileNameExtensionFilter("Arquivo PNG", "png"));
		 //Dialogo.addChoosableFileFilter(new FileNameExtensionFilter("Arquivo JPG", "jpg"));
		 Dialogo.setAcceptAllFileFilterUsed(false);

		 int Teste = Dialogo.showOpenDialog(this);
		 if (Teste == JFileChooser.APPROVE_OPTION) {
			 //txtEndereco.setText(Dialogo.getCurrentDirectory().getPath()+Dialogo.getSelectedFile().getName());
			 txtCheckSum.setText(FileClass.getAdler32CheckSumHexadecimal(Dialogo.getSelectedFile().toString()));
			 txtCheckSum.setToolTipText("CheckSum Adllder32 do arquivo '"+Dialogo.getSelectedFile().toString()+"'.");
		 } else {
			 //log.append("Open command cancelled by user." + newline);
		 }
}//GEN-LAST:event_btnSelecionarActionPerformed

	 private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		 // TODO add your handling code here:
		 Dimension Tela = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(
                (Tela.width - this.getWidth()) / 2,
                (Tela.height - this.getHeight()) / 2,
                this.getWidth(),
                this.getHeight());
        //this.setExtendedState(MAXIMIZED_BOTH); //Maximiza a tela
	 }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
			}
		});
	}
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnSelecionar;
   private javax.swing.JLabel lblArquivo1;
   private javax.swing.JTextField txtCheckSum;
   // End of variables declaration//GEN-END:variables
}
