/*
 * frmPrincipal.java
 * Created on 14/03/2012, 19:58:00
 * @author lunovox
 */
package calcinvesti;
import java.awt.Dimension;
import java.awt.Toolkit;

public class frmPrincipal extends javax.swing.JFrame {
	public frmPrincipal() {
		initComponents();
		Dimension Tela = Toolkit.getDefaultToolkit().getScreenSize();
		this.setBounds(
			(Tela.width - this.getWidth()) / 2,
			(Tela.height - this.getHeight()) / 2,
			this.getWidth(),
			this.getHeight()
		);
		calcInvestimento();
	}

	public void calcInvestimento() {
		CalculadoraFinanceira finCalc= new CalculadoraFinanceira(
			Float.parseFloat(spnAplicacaoMensal.getValue().toString()),
			Float.parseFloat(spnJurosDeRendimento.getValue().toString()),
			Integer.parseInt(spnTempoAplicado.getValue().toString())
		);
		txtAplicacaoTotal.setText(finCalc.getFarmatoMoedaNacional(finCalc.getAplicacaoMonetariaTotal()));
		txtRendimentoUltimoMes.setText(finCalc.getFarmatoMoedaNacional(finCalc.getRendimentoMonetarioUltimoMes()));
		txtRendimenTotal.setText("(+"+finCalc.getArredondado(finCalc.getRendimentoPercentualTotal(),2)+"%) "+finCalc.getFarmatoMoedaNacional(finCalc.getRendimentoMonetarioTotal()));
		txtSaldoAcumulado.setText(finCalc.getFarmatoMoedaNacional(finCalc.getSaldoMonetarioTotal()));
		//Runtime Executador = Runtime.getRuntime();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      spnAplicacaoMensal = new javax.swing.JSpinner();
      jLabel2 = new javax.swing.JLabel();
      spnJurosDeRendimento = new javax.swing.JSpinner();
      jLabel3 = new javax.swing.JLabel();
      spnTempoAplicado = new javax.swing.JSpinner();
      jLabel4 = new javax.swing.JLabel();
      txtAplicacaoTotal = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txtRendimenTotal = new javax.swing.JTextField();
      jLabel6 = new javax.swing.JLabel();
      txtSaldoAcumulado = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      txtRendimentoUltimoMes = new javax.swing.JTextField();
      btnExplicacao = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("Calculadora de Fundo de Investimento");
      setResizable(false);

      jLabel1.setText("Aplicação Mensal (R$):");

      spnAplicacaoMensal.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1000.96f), Float.valueOf(0.0f), Float.valueOf(10000.0f), Float.valueOf(0.01f)));
      spnAplicacaoMensal.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            spnAplicacaoMensalStateChanged(evt);
         }
      });

      jLabel2.setText("Juros de Rendimento (%):");

      spnJurosDeRendimento.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(1.0f), Float.valueOf(0.0f), Float.valueOf(10.0f), Float.valueOf(0.01f)));
      spnJurosDeRendimento.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            spnJurosDeRendimentoStateChanged(evt);
         }
      });

      jLabel3.setText("Tempo Aplicado (Meses):");

      spnTempoAplicado.setModel(new javax.swing.SpinnerNumberModel(240, 6, 480, 6));
      spnTempoAplicado.addChangeListener(new javax.swing.event.ChangeListener() {
         public void stateChanged(javax.swing.event.ChangeEvent evt) {
            spnTempoAplicadoStateChanged(evt);
         }
      });

      jLabel4.setText("Aplicação Total (R$):");

      txtAplicacaoTotal.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
      txtAplicacaoTotal.setEditable(false);
      txtAplicacaoTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtAplicacaoTotal.setText("R$ 0,00");

      jLabel5.setText("Rendimento Total (R$):");

      txtRendimenTotal.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
      txtRendimenTotal.setEditable(false);
      txtRendimenTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtRendimenTotal.setText("R$ 0,00");

      jLabel6.setText("Saldo Acumulado (R$):");

      txtSaldoAcumulado.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
      txtSaldoAcumulado.setEditable(false);
      txtSaldoAcumulado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtSaldoAcumulado.setText("R$ 0,00");

      jLabel7.setText("Rendimento do Ultimo Mês(R$):");

      txtRendimentoUltimoMes.setBackground(java.awt.SystemColor.inactiveCaptionBorder);
      txtRendimentoUltimoMes.setEditable(false);
      txtRendimentoUltimoMes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
      txtRendimentoUltimoMes.setText("R$ 0,00");

      btnExplicacao.setText("Explicação");
      btnExplicacao.setEnabled(false);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnExplicacao)
               .addComponent(spnJurosDeRendimento, 0, 0, Short.MAX_VALUE)
               .addComponent(spnTempoAplicado, 0, 0, Short.MAX_VALUE)
               .addComponent(spnAplicacaoMensal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
               .addComponent(txtAplicacaoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
               .addComponent(txtRendimenTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
               .addComponent(txtSaldoAcumulado, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
               .addComponent(txtRendimentoUltimoMes, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(jLabel1)
               .addComponent(spnAplicacaoMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(jLabel2)
               .addComponent(spnJurosDeRendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
               .addComponent(jLabel3)
               .addComponent(spnTempoAplicado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(txtAplicacaoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel7)
               .addComponent(txtRendimentoUltimoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel5)
               .addComponent(txtRendimenTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(txtSaldoAcumulado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnExplicacao)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void spnAplicacaoMensalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAplicacaoMensalStateChanged
	    calcInvestimento();
    }//GEN-LAST:event_spnAplicacaoMensalStateChanged
    private void spnJurosDeRendimentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnJurosDeRendimentoStateChanged
	    calcInvestimento();
    }//GEN-LAST:event_spnJurosDeRendimentoStateChanged
    private void spnTempoAplicadoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnTempoAplicadoStateChanged
	    calcInvestimento();
    }//GEN-LAST:event_spnTempoAplicadoStateChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new frmPrincipal().setVisible(true);
			}
		});
	}
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnExplicacao;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JSpinner spnAplicacaoMensal;
   private javax.swing.JSpinner spnJurosDeRendimento;
   private javax.swing.JSpinner spnTempoAplicado;
   private javax.swing.JTextField txtAplicacaoTotal;
   private javax.swing.JTextField txtRendimenTotal;
   private javax.swing.JTextField txtRendimentoUltimoMes;
   private javax.swing.JTextField txtSaldoAcumulado;
   // End of variables declaration//GEN-END:variables
}
