/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TMWMaker2010FrmLinguagem.java
 *
 * Created on Mar 19, 2010, 7:37:03 PM
 */

package tmwmaker2010;

/**
 *
 * @author indigovox
 */
public class TMWMaker2010FrmLinguagem extends javax.swing.JFrame {

    /** Creates new form TMWMaker2010FrmLinguagem */
    public TMWMaker2010FrmLinguagem() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jToggleButton1 = new javax.swing.JToggleButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jList1 = new javax.swing.JList();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(tmwmaker2010.TMWMaker2010App.class).getContext().getResourceMap(TMWMaker2010FrmLinguagem.class);
      setTitle(resourceMap.getString("FrmLinguagens.title")); // NOI18N
      setName("FrmLinguagens"); // NOI18N
      setResizable(false);

      jToggleButton1.setMnemonic('R');
      jToggleButton1.setText(resourceMap.getString("BtnFechar.text")); // NOI18N
      jToggleButton1.setName("BtnFechar"); // NOI18N

      jScrollPane1.setName("jScrollPane1"); // NOI18N

      jList1.setModel(new javax.swing.AbstractListModel() {
         String[] strings = { "Português brasileiro", "Inglês (english-.xml)", "Espanhou (spain.xml)", "Esperanto (esparanto.xml)" };
         public int getSize() { return strings.length; }
         public Object getElementAt(int i) { return strings[i]; }
      });
      jList1.setName("LstLinguagens"); // NOI18N
      jList1.setSelectedIndex(0);
      jScrollPane1.setViewportView(jList1);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
               .addComponent(jToggleButton1))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jToggleButton1)
            .addContainerGap())
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TMWMaker2010FrmLinguagem().setVisible(true);
            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JList jList1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JToggleButton jToggleButton1;
   // End of variables declaration//GEN-END:variables

}
