/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.net.URISyntaxException;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rtextarea.RTextScrollPane;
/**
 *
 * @author Danilo
 */

class MyCustomFilter extends javax.swing.filechooser.FileFilter {
        @Override
        public boolean accept(File file) {
            // Permite apenas diretórios ou arquivos com a extensão ".conf"
            return file.isDirectory() || file.getAbsolutePath().endsWith(".conf");
        }
        @Override
        public String getDescription() {
            // Esta descrição será exibida na caixa de diálogo,
            // hard-coded = ugly, deve ser feito via I18N
            return "Arquivo Conf (*.conf)";
        }
    } 

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      btnNovo = new javax.swing.JButton();
      btnAbrir = new javax.swing.JButton();
      jFileChooser1 = new javax.swing.JFileChooser();
      btnSalvar = new javax.swing.JButton();
      jFileChooser2 = new javax.swing.JFileChooser();
      scpPalco = new javax.swing.JScrollPane();
      atsPalco = new org.fife.ui.rsyntaxtextarea.RSyntaxTextArea();
      pnlBarraDeEstatus = new javax.swing.JPanel();
      lblBarraDeEstatus = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setTitle("TMW-Script Editor (Open Alfa 0.1.0)");
      addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
         public void mouseMoved(java.awt.event.MouseEvent evt) {
            formMouseMoved(evt);
         }
      });

      btnNovo.setText("Novo");
      btnNovo.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnNovoActionPerformed(evt);
         }
      });

      btnAbrir.setText("Abrir");
      btnAbrir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAbrirActionPerformed(evt);
         }
      });

      jFileChooser1.setFileFilter(new MyCustomFilter());

      btnSalvar.setText("Salvar");
      btnSalvar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnSalvarActionPerformed(evt);
         }
      });

      atsPalco.setColumns(20);
      atsPalco.setRows(5);
      atsPalco.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
         public void mouseMoved(java.awt.event.MouseEvent evt) {
            atsPalcoMouseMoved(evt);
         }
      });
      scpPalco.setViewportView(atsPalco);

      pnlBarraDeEstatus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

      lblBarraDeEstatus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/botoes/sbl_localhost-tmw.png"))); // NOI18N
      lblBarraDeEstatus.setText("Bem vindo ao TMW-ScriptEditor!");

      javax.swing.GroupLayout pnlBarraDeEstatusLayout = new javax.swing.GroupLayout(pnlBarraDeEstatus);
      pnlBarraDeEstatus.setLayout(pnlBarraDeEstatusLayout);
      pnlBarraDeEstatusLayout.setHorizontalGroup(
         pnlBarraDeEstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(pnlBarraDeEstatusLayout.createSequentialGroup()
            .addContainerGap()
            .addComponent(lblBarraDeEstatus, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addContainerGap())
      );
      pnlBarraDeEstatusLayout.setVerticalGroup(
         pnlBarraDeEstatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(lblBarraDeEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 17, Short.MAX_VALUE)
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
         .addComponent(pnlBarraDeEstatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(scpPalco, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addContainerGap())
      );

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAbrir, btnNovo, btnSalvar});

      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(btnNovo)
                  .addComponent(btnAbrir)
                  .addComponent(btnSalvar))
               .addGroup(layout.createSequentialGroup()
                  .addGap(12, 12, 12)
                  .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(scpPalco, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlBarraDeEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
	    this.setEnabled(false);
        new forms.NovoScript(this).setVisible(true);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
    int returnVal = jFileChooser1.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION) {
        File file = jFileChooser1.getSelectedFile();
        try {
          // What to do with the file, e.g. display it in a TextArea
          atsPalco.read( new FileReader( file.getAbsolutePath() ), null );
        } catch (IOException ex) {
          System.out.println("Problema ao acessar o arquivo "+file.getAbsolutePath());
        }
    } else {
        System.out.println("Acesso ao arquivo cancelado pelo usuário.");
    }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
             int returnVal = jFileChooser2.showSaveDialog(TelaPrincipal.this);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = jFileChooser2.getSelectedFile();
                try {
				if (file.exists()){
				JOptionPane.showConfirmDialog(null, "Arquivo já existe. \n Deseja sobrescrever?", "Aviso!", JOptionPane.YES_NO_OPTION);
				}
                                else {
                    BufferedWriter writer = new BufferedWriter(new FileWriter(file));
                    writer.write(atsPalco.getText());
                    writer.close();}
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        lblBarraDeEstatus.setText(String.format("Localizaçao do Mouse: [%d, %d]", evt.getX(), evt.getY()));
    }//GEN-LAST:event_formMouseMoved

    private void atsPalcoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_atsPalcoMouseMoved
        lblBarraDeEstatus.setText(String.format("Localizaçao do Mouse: [%d, %d]", evt.getX(), evt.getY()));
    }//GEN-LAST:event_atsPalcoMouseMoved

                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
        /*
        /*
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
   // Variables declaration - do not modify//GEN-BEGIN:variables
   public static org.fife.ui.rsyntaxtextarea.RSyntaxTextArea atsPalco;
   private javax.swing.JButton btnAbrir;
   private javax.swing.JButton btnNovo;
   private javax.swing.JButton btnSalvar;
   private javax.swing.JFileChooser jFileChooser1;
   private javax.swing.JFileChooser jFileChooser2;
   private javax.swing.JLabel lblBarraDeEstatus;
   private javax.swing.JPanel pnlBarraDeEstatus;
   private javax.swing.JScrollPane scpPalco;
   // End of variables declaration//GEN-END:variables
}
